version: "3"
services:
  react:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    # volume: /usr/src/app/node-modules
    # volumes:
    #   - /usr/src/app/node-modules
    #   - c:\workspace\docker\docker-react-app:/usr/src/app
    stdin_open: true
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    # volume: /usr/src/app/node-modules
    command: ["npm", "run", "test"]
        